### ISSUE TITLE
Integration on geotiffjs.github.io

### ISSUE THREAD

**Issue by constantinius** [GeoTIFF/geotiff.io#181]
Hi there!

I'm compiling a list of projects using geotiff.js, and I'd like to know if you are okay with me putting a link to geotiff.io on this page?

If so, do you have a small image and a short description I can put there?

Thanks and regards

**Comment by DanielJDufour** [comment]
Awesome!  Yes, that's okay with us.  

Description: Static website for viewing and analyzing GeoTIFF's in the browser
Image: http://app.geotiff.io/images/logomark.svg

Thanks so much! :-)

**Comment by DanielJDufour** [comment]
@constantinius ,  here's a better image at 553 x 290 pixels
![geotiffio](https://user-images.githubusercontent.com/4313463/39189422-35fb241a-47a0-11e8-844b-dc8332e2b393.png)

Original image is:
![fresno](https://user-images.githubusercontent.com/4313463/39189530-70539f02-47a0-11e8-83b5-b0a162cbe59f.png)

**Comment by DanielJDufour** [comment]
@constantinius , awesome and thanks!
