### ISSUE TITLE
Reduced image quality

### ISSUE THREAD

**Issue by elielwaltrick** [GeoTIFF/geotiff.io#232]
Hello guys! Thank you for this great project, it's very useful!

So, this is not really a bug report or anything, more like a request for information.

I noticed that the image quality is reduced when compared to QGIS for example. Is this normal behavior? Is there something that can be done to improve image quality?

geotiff.io: https://i.imgur.com/HllivSc.png

QGIS: https://i.imgur.com/OR1RK50.png

**Comment by DanielJDufour** [comment]
Hello. Yes, you can improve the resolution! Please read https://github.com/GeoTIFF/geotiff.io/blob/master/ADVANCED_FEATURES.md#adjusting-resolution and let me know if this helps :-) 

You're not the only one to ask, which leads me to believe we should make this info more clear.  Perhaps we should create a settings tool or allow the user to specify a resolution in the load tool.  Open to your thoughts!
