### ISSUE TITLE
SkySat COG loading forever

### ISSUE THREAD

**Issue by m-mohr** [GeoTIFF/geotiff.io#260]
**Describe the bug**
I've tried to visualize the COG https://s3-us-west-2.amazonaws.com/planet-disaster-data/hurricane-harvey/SkySat_Freeport_s03_20170831T162740Z3.tif on geotiff.io. Unfortunately, it was loading "forever" (aborted after some time). It looked like it's downloading the whole 700MB file. I had hoped it would load quicker as it's a COG though?!

**To Reproduce**

1. Go to geotiff.io
2. Use the URL https://s3-us-west-2.amazonaws.com/planet-disaster-data/hurricane-harvey/SkySat_Freeport_s03_20170831T162740Z3.tif
3. Wait...

**Expected behavior**
Load COG quickly via HTTP Range requests.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 89.0

**Comment by DanielJDufour** [comment]
Unfortunately, GeoTIFF.io doesn't support COGs yet.  I have a couple of things to do first, including finishing the next major release of GeoRaster. and adding COG support to GeoBlaze.
